version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  celery:
    build: .
    command: celery -A CVProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DEBUG: ${DEBUG}
      DOCKER: True

volumes:
  postgres_storage:
